### ISSUE TITLE
add slide(s) on licensing & attribution best practices

### ISSUE THREAD

**Issue by bbest** [eco-data-science/github-intro#2]
Hi @jules32,

Per conversation yesterday with @jafflerbach R spatial talk at NCEAS, @mpsaloha brought up the need to give licensing and attribution. NSF and other funders want crediting and good to always include licensing. Would be good to include a slide or 2 on "best practices" in this presentation for the December talk. When creating a **new** Github repository, you're offered 2 recommended options:

  ![image](https://cloud.githubusercontent.com/assets/2837257/10080133/c32e7bd8-62a2-11e5-9a36-f9c538abe46a.png)
1. **Initialize this repository with a README**. Funders and organizational affiliations can be included here.
2. **Add a license**.  Clicking on the info icon provides the following guidance:
   
   ![image](https://cloud.githubusercontent.com/assets/2837257/10080210/3ddc756a-62a3-11e5-88ac-6cf8d9bf0467.png)

@mpsaloha also mentioned [Creative Commons licenses](https://creativecommons.org/choose/), particularly applicable to media such as graphics and presentations.

**Comment by jules32** [comment]
Thanks for this BB, I'll add it to the talk!

On Thursday, September 24, 2015, Ben Best notifications@github.com wrote:

> Hi @jules32 https://github.com/jules32,
> 
> Per conversation yesterday with @jafflerbach
> https://github.com/jafflerbach R spatial talk at NCEAS, @mpsaloha
> https://github.com/mpsaloha brought up the need to give licensing and
> attribution. NSF and other funders want crediting and good to always
> include licensing. Would be good to include a slide or 2 on "best
> practices" in this presentation for the December talk. When creating a
> _new_ Github repository, you're offered 2 recommended options:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/2837257/10080133/c32e7bd8-62a2-11e5-9a36-f9c538abe46a.png
> 
>    1.
> 
>    _Initialize this repository with a README_. Funders and organizational
>    affiliations can be included here.
>    2.
> 
>    _Add a license_. Clicking on the info icon provides the following
>    guidance:
> 
>    [image: image]
>    https://cloud.githubusercontent.com/assets/2837257/10080210/3ddc756a-62a3-11e5-88ac-6cf8d9bf0467.png
> 
> @mpsaloha https://github.com/mpsaloha also mentioned Creative Commons
> licenses https://creativecommons.org/choose/, particularly applicable
> to media such as graphics and presentations.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eco-data-science/github-intro/issues/2.

## 

Julia Stewart Lowndes, PhD
Project Scientist, Ocean Health Index
National Center for Ecological Analysis and Synthesis (NCEAS)
University of California, Santa Barbara
735 State Street, Suite 300
Santa Barbara, CA, 93101, USA
ohi http://www.oceanhealthindex.org/ • ohi-science
http://ohi-science.org/ • github https://github.com/jules32 • twitter
https://twitter.com/juliesquid

**Comment by jules32** [comment]
done!
