### ISSUE TITLE
can't commit from git window in rstudio

### ISSUE THREAD

**Issue by afredston** [eco-data-science/github-intro#3]
I (hopefully) followed the instructions from our github intro workshop and created a new repository for some research I'm doing and cloned it while starting a new R project. However, when I try to commit any code from rstudio's git window, I get this error: 

fatal: Unable to create '/Users/alexa/GitHub/species-traits/.git/index.lock': File exists.

I didn't find many consistent answers from Google and I thought one of you might know how to solve this one!

**Comment by afredston** [comment]
Update: this spontaneously resolved (hooray!) so I'm closing the issue. However, if anyone knows how this error arises or how to avoid it in the future, let me know!

**Comment by jules32** [comment]
Hi Alexa!

I had this error a few days ago and found the solution here on
stackoverflow.com
http://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists
.

If you know how to use the command line, go your working directory and type
`rm -f ./.git/index.lock`.

If you want to work from R, make sure you're in the right working directory
and type `system('rm -f ./.git/index.lock')`

Cheers,
Julie

On Fri, Sep 25, 2015 at 11:49 AM, Alexa Fredston-Hermann <
notifications@github.com> wrote:

> Update: this spontaneously resolved (hooray!) so I'm closing the issue.
> However, if anyone knows how this error arises or how to avoid it in the
> future, let me know!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eco-data-science/github-intro/issues/3#issuecomment-143319693
> .

## 

Julia Stewart Lowndes, PhD
Project Scientist, Ocean Health Index
National Center for Ecological Analysis and Synthesis (NCEAS)
University of California, Santa Barbara
735 State Street, Suite 300
Santa Barbara, CA, 93101, USA
ohi http://www.oceanhealthindex.org/ • ohi-science
http://ohi-science.org/ • github https://github.com/jules32 • twitter
https://twitter.com/juliesquid
